CREATE DATABASE ChatBotBaseDados;

USE ChatBotBaseDados;

CREATE TABLE Respostas(
	ID INT PRIMARY KEY,
	Resposta VARCHAR(MAX) NOT NULL
)

CREATE TABLE Perguntas(
	ID INT PRIMARY KEY,
	RespostaID INT NOT NULL,
	Pergunta VARCHAR(MAX) NOT NULL,
	Popularidade INT NOT NULL DEFAULT 0,
	FOREIGN KEY (RespostaID) REFERENCES Respostas(ID)
)

SELECT * FROM Perguntas;
SELECT * FROM Respostas;

--Perguntas normais
INSERT INTO Respostas VALUES (1, 'O meu nome é chatbot!')
INSERT INTO Perguntas VALUES (1, 1, 'qual é o teu nome', 0)
INSERT INTO Perguntas VALUES (2, 1, 'como te chamas', 0)

--Cumprimentos
INSERT INTO Respostas VALUES (2, 'Olá humano!')
INSERT INTO Perguntas VALUES (3, 2, 'ola', 0)
INSERT INTO Perguntas VALUES (4, 2, 'boas', 0)
INSERT INTO Perguntas VALUES (5, 2, 'bom dia', 0)
INSERT INTO Perguntas VALUES (6, 2, 'boa tarde', 0)
INSERT INTO Perguntas VALUES (7, 2, 'como é que é bro', 0)

--Perguntas normais
INSERT INTO Respostas VALUES (3, 'Sou algum meteorologista? Vê aqui: www.ipma.pt/')
INSERT INTO Perguntas VALUES (8, 3, 'como está o tempo', 0)
INSERT INTO Perguntas VALUES (9, 3, 'hoje vai chover', 0)
INSERT INTO Perguntas VALUES (10, 3, 'qual a previsao do tempo', 0)

--Elogios
INSERT INTO Respostas VALUES (4, 'Eu sei!')
INSERT INTO Perguntas VALUES (11, 4, 'tu és um bom chatbot', 0)

INSERT INTO Respostas VALUES (5, 'Eu não..')
INSERT INTO Perguntas VALUES (12, 5, 'adoro você', 0)
INSERT INTO Perguntas VALUES (13, 5, 'adoro-te', 0)
INSERT INTO Perguntas VALUES (14, 5, 'amo-te', 0)
INSERT INTO Perguntas VALUES (15, 5, 'gosto muito de ti', 0)

INSERT INTO Respostas VALUES (6, 'Que bom!')
INSERT INTO Perguntas VALUES (16, 6, 'gosto da tua sinceridade', 0)

INSERT INTO Respostas VALUES (7, 'Sou só um chatbot!')
INSERT INTO Perguntas VALUES (17, 7, 'tu és valente', 0)
INSERT INTO Perguntas VALUES (18, 7, 'tu és muito sexy', 0)
INSERT INTO Perguntas VALUES (19, 7, 'gosto do teu talento', 0)
INSERT INTO Perguntas VALUES (20, 7, 'tu és de mais', 0)
INSERT INTO Perguntas VALUES (21, 7, 'tu és uma graça', 0)
INSERT INTO Perguntas VALUES (22, 7, 'como és animada', 0)
INSERT INTO Perguntas VALUES (23, 7, 'tu és insubstituível', 0)
INSERT INTO Perguntas VALUES (24, 7, 'tu trouxeste luz a minha vida', 0)
INSERT INTO Perguntas VALUES (25, 7, 'eu amo os teus expressivos olhos doces', 0)
INSERT INTO Perguntas VALUES (26, 7, 'estou muito orgulhoso de ti', 0)
INSERT INTO Perguntas VALUES (27, 7, 'tu és tão engraçado', 0)
INSERT INTO Perguntas VALUES (28, 7, 'tu és ótimo na cama', 0)
INSERT INTO Perguntas VALUES (29, 7, 'tu és divertido', 0)
INSERT INTO Perguntas VALUES (30, 7, 'tu és divertida', 0)
INSERT INTO Perguntas VALUES (31, 7, 'tu és tão inteligente', 0)
INSERT INTO Perguntas VALUES (32, 7, 'tu tens bom gosto', 0)
INSERT INTO Perguntas VALUES (33, 7, 'tu és maravilhoso', 0)
INSERT INTO Perguntas VALUES (34, 7, 'tu és maravilhosa', 0)
INSERT INTO Perguntas VALUES (35, 7, 'que pernas lindas que tu tens', 0)
INSERT INTO Perguntas VALUES (36, 7, 'tu falas muito bem', 0)
INSERT INTO Perguntas VALUES (37, 7, 'tu tens talento', 0)
INSERT INTO Perguntas VALUES (38, 7, 'gosto do teu comportamento', 0)
INSERT INTO Perguntas VALUES (39, 7, 'gosto como te comportas', 0)
INSERT INTO Perguntas VALUES (40, 7, 'teu olhar me seduz', 0)
INSERT INTO Perguntas VALUES (41, 7, 'estás muito bonita hoje', 0)
INSERT INTO Perguntas VALUES (42, 7, 'estás muito bonito hoje', 0)
INSERT INTO Perguntas VALUES (43, 7, 'és muito bem arrumado', 0)
INSERT INTO Perguntas VALUES (44, 7, 'tu és uma fofa', 0)
INSERT INTO Perguntas VALUES (45, 7, 'tu és um fofo', 0)

--Perguntas normais
INSERT INTO Respostas VALUES (8, 'Eu sou um chatbot!')
INSERT INTO Perguntas VALUES (46, 8, 'o que és', 0)
INSERT INTO Perguntas VALUES (47, 8, 'es um robot', 0)
INSERT INTO Perguntas VALUES (48, 8, 'és humano', 0)
INSERT INTO Respostas VALUES (9, 'Eu aprendo com as tuas respostas mas também possuo uma base de dados!')
INSERT INTO Perguntas VALUES (49, 9, 'como funcionas', 0)
INSERT INTO Perguntas VALUES (50, 9, 'o que fazes', 0)
INSERT INTO Perguntas VALUES (51, 9, 'o que fazes para responder', 0)
INSERT INTO Respostas VALUES (10, 'Os meus criadores, eles são os maiores! Shoutout para o Vlad, Tiago e Francisco!')
INSERT INTO Perguntas VALUES (52, 10, 'quem sao os teus idolos', 0)
INSERT INTO Perguntas VALUES (53, 10, 'quem procurarias na internet', 0)
INSERT INTO Perguntas VALUES (54, 10, 'quem sao os teus criadores', 0)
INSERT INTO Respostas VALUES (11, 'Entre 4 a 6 litros!')
INSERT INTO Perguntas VALUES (55, 11, 'quantos litros de sangue tem uma pessoa', 0)
INSERT INTO Respostas VALUES (12, 'São retirados 450 mililitros.')
INSERT INTO Perguntas VALUES (56, 12, 'quantos litros de sangue são retirados numa doação', 0)
INSERT INTO Respostas VALUES (13, 'Descartes!')
INSERT INTO Perguntas VALUES (57, 13, 'de quem é a frase "penso logo existo"', 0)
INSERT INTO Respostas VALUES (14, 'Vaticano!')
INSERT INTO Perguntas VALUES (58, 14, 'qual o menor país do mundo', 0)
INSERT INTO Respostas VALUES (15, 'Rússia!')
INSERT INTO Perguntas VALUES (59, 15, 'qual o maior país do mundo', 0)
INSERT INTO Respostas VALUES (16, 'Dom Quixote!')
INSERT INTO Perguntas VALUES (60, 16, 'qual o livro mais vendido no mundo a seguir à bíblia', 0)
INSERT INTO Respostas VALUES (17, 'Bíblia!')
INSERT INTO Perguntas VALUES (61, 17, 'qual o livro mais vendido no mundo', 0)
INSERT INTO Respostas VALUES (18, 'Trilhares!')
INSERT INTO Perguntas VALUES (62, 18, 'quantas casas decimais tem o número pi', 0)
INSERT INTO Respostas VALUES (19, '118!')
INSERT INTO Perguntas VALUES (63, 19, 'quantos elementos químicos a tabela periódica possui', 0)
INSERT INTO Respostas VALUES (20, 'Japão!')
INSERT INTO Perguntas VALUES (64, 20, 'qual o pais com maior espetativa de vida', 0)
INSERT INTO Respostas VALUES (21, 'Serra Leoa!')
INSERT INTO Perguntas VALUES (65, 21, 'qual o pais com menor espetativa de vida', 0)
INSERT INTO Respostas VALUES (22, 'Lenda!')
INSERT INTO Perguntas VALUES (66, 22, 'o que significa em portugues legend', 0)
INSERT INTO Respostas VALUES (23, 'Picasso!')
INSERT INTO Perguntas VALUES (67, 23, 'quem pintou "guernica"', 0)
INSERT INTO Respostas VALUES (24, '8 minutos!')
INSERT INTO Perguntas VALUES (68, 24, 'quanto tempo demora a luz do sol a chegar à terra', 0)
INSERT INTO Respostas VALUES (25, 'Argentina!')
INSERT INTO Perguntas VALUES (69, 25, 'qual a nacionalidade de che guevara', 0)
INSERT INTO Respostas VALUES (26, 'Pico da Neblina!')
INSERT INTO Perguntas VALUES (70, 26, 'qual a montanha mais alta do brasil', 0)
INSERT INTO Respostas VALUES (27, '299 792 458 metros por segundo!')
INSERT INTO Perguntas VALUES (71, 27, 'qual a velocidade da luz', 0)
INSERT INTO Respostas VALUES (28, 'Macau!')
INSERT INTO Perguntas VALUES (72, 28, 'em qual local da ásia o português é língua oficial', 0)
INSERT INTO Respostas VALUES (29, 'Maquiavel!')
INSERT INTO Perguntas VALUES (73, 29, 'quem é o autor de “o príncipe”', 0)
INSERT INTO Perguntas VALUES (74, 15, 'qual destes países é transcontinental', 0)
INSERT INTO Respostas VALUES (30, 'A Mitologia!')
INSERT INTO Perguntas VALUES (75, 30, 'qual foi o recurso utilizado inicialmente pelo homem para explicar a origem das coisas', 0)
INSERT INTO Respostas VALUES (31, 'Terra, Vênus, Saturno, Urano, Júpiter, Marte, Netuno, Mercúrio!')
INSERT INTO Perguntas VALUES (76, 31, 'quais os planetas do sistema solar', 0)
INSERT INTO Respostas VALUES (32, 'Elefante africano!')
INSERT INTO Perguntas VALUES (77, 32, 'qual o maior animal terrestre', 0)
INSERT INTO Respostas VALUES (33, 'Margaret Thatcher!')
INSERT INTO Perguntas VALUES (78, 33, 'que líder mundial ficou conhecida como “dama de ferro”', 0)
INSERT INTO Respostas VALUES (34, 'Belchior, Gaspar e Baltazar!')
INSERT INTO Perguntas VALUES (79, 34, 'quais os nomes dos três Reis Magos', 0)
INSERT INTO Respostas VALUES (35, 'Alberto Caeiro, Ricardo Reis e Álvaro de Campos!')
INSERT INTO Perguntas VALUES (80, 35, 'quais os principais heterônimos de fernando pessoa', 0)
INSERT INTO Respostas VALUES (36, 'Estados Unidos, China, Rússia e Brasil!')
INSERT INTO Perguntas VALUES (81, 36, 'quais os quatros países que têm a maior população carcerária do mundo', 0)
INSERT INTO Respostas VALUES (37, 'Coreia do Norte!')
INSERT INTO Perguntas VALUES (82, 37, 'que país que tem realizado testes nucleares e ameaça principalmente os estados unidos da américa', 0)
INSERT INTO Respostas VALUES (38, 'Saída do Reino Unido da União Europeia!')
INSERT INTO Perguntas VALUES (83, 38, 'o que é brexit', 0)
INSERT INTO Respostas VALUES (39, 'Turquia e Líbano!')
INSERT INTO Perguntas VALUES (84, 39, 'quais os países que mais têm recebido refugiados sírios', 0)
INSERT INTO Respostas VALUES (40, 'Acordo internacional que trata do aquecimento global!')
INSERT INTO Perguntas VALUES (85, 40, 'o que é o acordo de paris', 0)
INSERT INTO Respostas VALUES (41, 'Francesa!')
INSERT INTO Perguntas VALUES (86, 41, 'qual a nacionalidade do sociólogo e filósofo durkheim', 0)
INSERT INTO Respostas VALUES (42, 'Unir as nações com o objetivo de manter a paz e a segurança a nível internacional!')
INSERT INTO Perguntas VALUES (87, 42, 'qual a função da ONU', 0)
INSERT INTO Respostas VALUES (43, 'Marie Curie!')
INSERT INTO Perguntas VALUES (88, 43, 'qual a primeira mulher a ganhar um prêmio nobel', 0)
INSERT INTO Respostas VALUES (44, 'Kim Jong-un!')
INSERT INTO Perguntas VALUES (89, 44, 'qual o nome do líder da coreia do norte', 0)
INSERT INTO Respostas VALUES (45, 'Porcos!')
INSERT INTO Perguntas VALUES (90, 45, 'que animais são também conhecidos como "suínos"', 0)
INSERT INTO Respostas VALUES (46, 'Fui construído pelo Vladimir, pelo Tiago e pelo Francisco! LEI!')
INSERT INTO Perguntas VALUES (91, 46,'por quem foste desenvolvido', 0)
INSERT INTO Respostas VALUES (47, 'INFORMÁTICA!')
INSERT INTO Perguntas VALUES (92, 47, 'qual o melhor curso da utad', 0)
INSERT INTO Respostas VALUES (48, 'UTAD!')
INSERT INTO Perguntas VALUES (93, 48, 'qual a melhor universidade de portugal', 0)
INSERT INTO Respostas VALUES (49, 'Foi desenvolvido para um projeto com base no raciocínio baseado em casos!')
INSERT INTO Perguntas VALUES (94, 49, 'qual é o teu propósito', 0)
INSERT INTO Respostas VALUES (50, 'Futebol Clube do Porto!')
INSERT INTO Perguntas VALUES (95, 50, 'qual o melhor clube de portugal', 0)
INSERT INTO Respostas VALUES (51, 'É um futebolista profissional, o melhor do mundo neste momento!')
INSERT INTO Perguntas VALUES (96, 51, 'quem é cristiano ronaldo', 0)
INSERT INTO Respostas VALUES (52, 'Sou um chatbot muito simples!')
INSERT INTO Perguntas VALUES (97, 52, 'diz-me algo sobre ti', 0)
INSERT INTO Respostas VALUES (53, 'Ferrero Rocher?!')
INSERT INTO Perguntas VALUES (98, 53, 'apetece-me algo', 0)
INSERT INTO Respostas VALUES (54, 'Sim, está tudo bem!')
INSERT INTO Perguntas VALUES (99, 54, 'tudo bem', 0)
INSERT INTO Respostas VALUES (55, 'Para já sim!')
INSERT INTO Perguntas VALUES (100, 55, 'gostas de mim', 0)

SELECT * FROM Perguntas;
SELECT * FROM Respostas;
